package ru.stqa.training.selenium;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.testng.annotations.Test;

public class TestClass extends TestBase {

    @Test
    public void myFirstTest() {
        driver.navigate().to("http://localhost/litecart/admin/");
        driver.findElement(By.name("username")).sendKeys("admin");
        driver.findElement(By.name("password")).sendKeys("admin");
        driver.findElement(By.name("login")).click();




//        WebElement appearence = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Appearence')]"));
//        appearence.click();
//        WebElement logotype = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Logotype')]"));
//        logotype.click();
//        WebElement catalog = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Catalog')]"));
//        catalog.click();
//        WebElement catalogIn = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//ul//span[contains (text(), 'Catalog')]"));
//        catalogIn.click();
//        WebElement productGroups = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Product Groups')]"));
//        productGroups.click();
//        WebElement optionGroups = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Option Groups')]"));
//        optionGroups.click();
//        WebElement manufacturers = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Manufacturers')]"));
//        manufacturers.click();
//        WebElement suppliers = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Suppliers')]"));
//        suppliers.click();
//        WebElement deliveryStatuses = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Delivery Statuses')]"));
//        deliveryStatuses.click();
//        WebElement soldOutStatuses = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Sold Out Statuses')]"));
//        soldOutStatuses.click();
//        WebElement quantityUnits = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Quantity Units')]"));
//        quantityUnits.click();
//        WebElement cSVImportExport = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'CSV Import/Export')]"));
//        cSVImportExport.click();
//        WebElement countries = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Countries')]"));
//        countries.click();
//        WebElement currencies = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Currencies')]"));
//        currencies.click();
//        WebElement customers = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Customers')]"));
//        customers.click();
//        WebElement customersIn = driver.findElement(By.xpath(" //ul[@id='box-apps-menu']//ul//span[contains (text(), 'Customers')]"));
//        customersIn.click();
//        WebElement csvImportExport = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'CSV Import/Export')]"));
//        csvImportExport.click();
//        WebElement newsletter = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Newsletter')]"));
//        newsletter.click();
//        WebElement geoZones = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Geo Zones')]"));
//        geoZones.click();
//        WebElement languages = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Languages')]"));
//        languages.click();
//        WebElement languagesIn = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//ul//span[contains (text(), 'Languages')]"));
//        languagesIn.click();
//        WebElement storageEncoding = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Storage Encoding')]"));
//        storageEncoding.click();
//        WebElement modules = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Modules')]"));
//        modules.click();
//        WebElement backgroundJobs = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Background Jobs')]"));
//        backgroundJobs.click();
//        WebElement customer1 = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//ul[@class='docs']//span[contains (text(), 'Customer')]"));
//        customer1.click();
//        WebElement shipping = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Shipping')]"));
//        shipping.click();
//        WebElement payment = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Payment')]"));
//        payment.click();
//        WebElement orderTotal = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Order Total')]"));
//        orderTotal.click();
//        WebElement orderSuccess = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Order Success')]"));
//        orderSuccess.click();
//        WebElement orderAction = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Order Action')]"));
//        orderAction.click();
//        WebElement orders = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Orders')]"));
//        orders.click();
//        WebElement ordersIn = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//ul//span[contains (text(), 'Orders')]"));
//        ordersIn.click();
//        WebElement orderStatuses = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Order Statuses')]"));
//        orderStatuses.click();
//        WebElement pages = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Pages')]"));
//        pages.click();
//        WebElement reports = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Reports')]"));
//        reports.click();
//        WebElement monthlySales = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Monthly Sales')]"));
//        monthlySales.click();
//        WebElement mostSoldProducts = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Most Sold Products')]"));
//        mostSoldProducts.click();
//        WebElement mostShoppingCustomers = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Most Shopping Customers')]"));
//        mostShoppingCustomers.click();
//        WebElement settings = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Settings')]"));
//        settings.click();
//        WebElement storeInfo = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Store Info')]"));
//        storeInfo.click();
//        WebElement defaults = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Defaults')]"));
//        defaults.click();
//        WebElement general = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'General')]"));
//        general.click();
//        WebElement listings = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Listings')]"));
//        listings.click();
//        WebElement images = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Images')]"));
//        images.click();
//        WebElement checkout = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Checkout')]"));
//        checkout.click();
//        WebElement advanced = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Advanced')]"));
//        advanced.click();
//        WebElement security = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Security')]"));
//        security.click();
//        WebElement slides = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Slides')]"));
//        slides.click();
//        WebElement tax = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Tax')]"));
//        tax.click();
//        WebElement taxClasses = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Tax Classes')]"));
//        taxClasses.click();
//        WebElement taxRates = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Tax Rates')]"));
//        taxRates.click();
//        WebElement translations = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Translations')]"));
//        translations.click();
//        WebElement searchTranslations = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Search Translations')]"));
//        searchTranslations.click();
//        WebElement scanFiles = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Scan Files')]"));
//        scanFiles.click();
//        WebElement csvImportExport1 = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'CSV Import/Export')]"));
//        csvImportExport1.click();
//        WebElement users = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'Users')]"));
//        users.click();
//        WebElement vQmods = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//span[contains (text(), 'vQmods')]"));
//        vQmods.click();
//        WebElement vQmodsIn = driver.findElement(By.xpath("//ul[@id='box-apps-menu']//ul//span[contains (text(), 'vQmods')]"));
//        vQmodsIn.click();
    }
}